coverage:
    range: 60..80
    round: down
    precision: 2
    status:
        project:
            default:
                target: 75%
                threshold: 10%

comment:
    layout: " diff, flags, files"
    behavior: default
    require_changes: false
    require_base: false
    require_head: true
    hide_project_coverage: false
